ci_access:
  projects:
    # Allow CI jobs to deploy manifests in this project
    - id: louisgimeno72/solar-system
    
user_access:
  access_as:
    agent: {}
  projects:
    # Permit users to view the Kubernetes dashboard in this project
    - id: louisgimeno72/solar-system